name: electricity_price
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+10

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  syncfusion_flutter_charts: ^19.4.53
  splash_screen_view: ^3.0.0
  shimmer: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^9.7.0
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0
  fluttertoast: ^8.0.9
  dio: ^4.0.6
  json_serializable: ^6.4.0
  json_annotation: ^4.7.0
  retrofit: ^3.0.1+1
  flutter_bloc: ^8.1.1
  copy_with_extension: ^4.0.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  retrofit_generator: '>=4.0.0 <5.0.0'
  copy_with_extension_gen: ^4.0.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/ic_launcher.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
